# Generated by Django 2.0.5 on 2018-05-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0003_auto_20180430_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='possible_schedule',
            unique_together={('staff_id', 'day_id')},
        ),
    ]
