# Generated by Django 2.0.5 on 2018-05-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0004_auto_20180507_1406'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('day', 'time')},
        ),
    ]
