# Generated by Django 2.0.5 on 2018-05-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0005_auto_20180507_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('name', 'phone')},
        ),
    ]
