# Generated by Django 2.0.5 on 2018-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0006_auto_20180509_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='possible_N_days',
            field=models.IntegerField(blank=True, default=3),
        ),
        migrations.AlterField(
            model_name='staff',
            name='score',
            field=models.FloatField(blank=True, default=50),
        ),
    ]
