# Generated by Django 2.0.5 on 2018-05-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0007_auto_20180509_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='needs',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
