# Generated by Django 2.0.5 on 2018-05-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0008_day_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='newcomer',
            field=models.BooleanField(default=False),
        ),
    ]
