# Generated by Django 2.0.5 on 2018-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0009_staff_newcomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='needs_newcomer',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
