# Generated by Django 2.0.4 on 2018-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0011_auto_20180513_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='possible_schedule',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='max_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='min_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='day',
            name='time',
            field=models.CharField(choices=[('D', '선오픈'), ('D1', '후오픈'), ('D2', '준오픈'), ('M', '선미들'), ('M1', '미들1'), ('M2', '미들2'), ('M3', '미들3'), ('M4', '늦미들'), ('N', '선마감'), ('N1', '마감'), ('N2', '후마감')], max_length=5),
        ),
    ]
