# Generated by Django 2.0.5 on 2018-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso', '0012_auto_20180521_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='complete',
            new_name='max_complete',
        ),
        migrations.AddField(
            model_name='staff',
            name='min_complete',
            field=models.BooleanField(default=False),
        ),
    ]
